### ISSUE TITLE
在吗？我使用type为LeeTagViewStyleSelectSingle的时候设置itemRegularHeight，发现设置不同的值会影响图片文字之间的距离，怎么调整啊

### ISSUE THREAD

**Issue by gaojiewan** [leeboo741/LeeTagView#1]

**Comment by gaojiewan** [comment]
我暂时用的是富文本，已经解决问题了，还是期待能用text，给个star...

**Comment by leeboo741** [comment]
首先，非常感谢star，爱你哟。也很感谢和欢迎您提出的问题。确实当前的TagView还有不少的bug，当时写的时候太懒，没有进行全面测试，只是觉得需要这么个属性或者方法，就给加上了，但是具体的使用场景没有想的太明白。我会尽可能努力改进。
其次，非常抱歉，最近事情太多，让老板拖着去学习写Android和小程序了，刚刚忙完，所以才看到你的问题，请不要太介意，我确实是一个很懒的家伙。

关于问题，我重新看了一下代码。我发现这个问题和type的值没有关系，任何情况下，只要设置固定高度，都会引发该问题。
接下来可能会讲的很乱，因为我暂时还没能捋顺，想到什么说什么。错在什么地方呢，主要是几个方法中吧，tagView中的intrinsicContentSize、resettag以及tagbutton中的imageRectForContentRect和intrinsicContentSize。在tagview中通过intrinsicContentSize和resettag方法我计算了tagView的宽高，并设置了其中的tagbutton的宽高，在这两个方法中我又调用了tagButton的intrinsicContentSize来获取计算uibutton的内容宽高，并在tagButton的imageRectForContentRect规定了imageView的宽高相等，imageView的高度等于tagButton高度的一半，这种情况下，button的宽高其实早就已经算出来了，但是当setFrame的时候又没有去重新计算布局button，这时候button的frame变了，但是button的intrinsicContentSize没动，button中image变了，但是button还是记录的之前所占的位置大小，于是问题来了，当你固定高度的时候，图片就会相对的方法缩小，但是，image和button原本的宽高并没有相应变化，这就导致了imageView在盒子里向左坍缩，button的高度在坍缩，但是宽度没有变化，而label也不知道imageView宽度变小了，也没有跟随移动。大概是应该这么解释的。

改进方法我现在在想。主要有以下：
第一，重设button的约束，让image跟随宽高变化，label跟随image变化，并且要通知到tagView重新布局，但是想想这样还不如用UIView重新写一个item。还能顺便完善一下状态之类的显示，填一些坑。
第二，用UIView重写一个item，en……，感觉自己挖的坑太大，想的太多，工程浩大，写了一部分，还不能上传……
第三，取消了tagButton的imageRectForContentRect方法，通过viewmodel的contentPadding和imageAndLabelPadding来约束图片和label之间的间距以及内容和边线的间距，并且设置tagButton的contentVerticalAlignment和contentHorizontalAlignment 都等于center，而不再强制图片宽高相等了，就像UIButton一样，如果固定高度大于等于图片高度，自然会显示的很完美，但是当高度小于图片高度的时候，图片会有一定的挤压变形。当然，最关键的问题，图片间距解决了……

目前而言，我将要使用第三种方法，会在一段时间之后使用第二种解决方法，那将是2.0版本的问题（我会在2.0中取消一些状态和新增一些新的状态，并且修复一些老旧问题，还是祈祷我的懒病快点好吧……）。但是关于当前的解决方案，因为在修改测试中改了太多东西，我需要针对这个问题再多测试几次。当然，因为我太懒的，估计不会用太长时间的。

最后，再次感谢，真诚的感谢。谢谢。

**Comment by leeboo741** [comment]
嗯，可以下载试试，只要这次要注意使用的图标图片大小，最好选个合适大小的图标

**Comment by leeboo741** [comment]
昨天晚上回去想了想，重新采用了第二种方法，使用LeeTagItem 和 LeeTagItemViewModel 替换了 LeeTagButton 和 LeeTagViewModel，全新2.0版本，已经上传，可以下载使用。如果还有问题，欢迎继续提交。
