### ISSUE TITLE
在cell中LeeTagViewLineStyleMulti情况下复用问题

### ISSUE THREAD

**Issue by SinglePlme** [leeboo741/LeeTagView#2]
在LeeTagViewLineStyleSingle [模式下不管是view或者cell可以，但是在LeeTagViewLineStyleMulti模式，初次加载的时候会出现LeeTagViewLineStyleSingle，即只显示一行，刷新的情况下才会出现多行，但是这个时候会随cell滑动而多次数据加载，万分感谢。非常喜欢这个控件，希望能解答我的疑问，让它更完善一点
<img width="294" alt="2019-01-21 10 14 20" src="https://user-images.githubusercontent.com/18419589/51449144-ae9df280-1d65-11e9-9d59-5b6a3c8739a3.png">

**Comment by leeboo741** [comment]
您好，我看到这个问题了。简单看了一下，有点麻烦，不过我会尽快抽时间跟进解决。
首先，不是singleLine的问题，是计算高度出现的问题，有点麻烦，是个大Bug，一时间还没能定位到出问题的地方。如果可以的话，可以先试试给Cell一个高度属性，cellHeight，读取tagView的intrinsicContentSize的高度，然后告诉tableView，虽然还是有些问题，但是勉强还能用。
其次，多次数据加载的问题您可以看看是不是在给cell添加数据的时候重新AddTag了，但是在AddTag之前没有removeTags清空之前的数据造成的数据重复加载。我后面会考虑添加一个清空再添加的方法。
最后，非常感谢你的关注和喜欢，虽然能力有限，但是我会尽快的解决这个问题。谢谢。

**Comment by SinglePlme** [comment]
非常感谢您的回复，这个高度不算大问题，数据重复的问题我事先也尝试了下，用你封装的那个removeAllTags，又试着在-(void)addTag:(TagViewModel *)tag中先删除清空，再添加，但是没怎么起效

**Comment by leeboo741** [comment]
您好，我稍微改了一点东西，并且添加了一个tableView的使用例子，可以先看一下能不能对您有所帮助，如果还是有问题请继续提出。
当然还是有些的问题，因为时间上还是比较紧张，问题有点复杂，没能完全想通透，所以我还在想要怎么去解决。解决后会第一时间告知。
